apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.db.secretName }}
  labels:
    {{- include "oneclicktimer-backend.labels" . | nindent 4 }}
type: "Opaque"
data:
  MYSQL_DATABASE: {{ default "" .Values.mysql.auth.database | b64enc | quote }}
  MYSQL_USER: {{ default "" .Values.mysql.auth.username | b64enc | quote }}
  MYSQL_PASSWORD: {{ default "oneclicktimer" .Values.db.password | b64enc | quote }}
  mysql-password: {{ default "oneclicktimer" .Values.db.password | b64enc | quote }}
  mysql-root-password: {{ default "root" .Values.db.rootPassword | b64enc | quote }}
